name: Python CI

on:
  push:
    paths:
      - 'server/**'
      - 'cv_engine/**'
      - 'pyproject.toml'
      - 'requirements*.txt'
  pull_request:
    paths:
      - 'server/**'
      - 'cv_engine/**'
      - 'pyproject.toml'
      - 'requirements*.txt'

jobs:
  tests:
    name: Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install build tooling
        run: python -m pip install --upgrade pip wheel setuptools

      - name: Install base dependencies
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt || true
          fi

      - name: Install dev dependencies
        run: |
          if [ -f requirements-dev.txt ]; then
            pip install -r requirements-dev.txt
          fi

      - name: Install tooling
        run: |
          pip install "pytest>=7" "pytest-cov" "mypy" "ruff" "httpx" "uvicorn[standard]"

      - name: Install package
        run: pip install -e .[test] || pip install -e .

      - name: Ruff
        run: ruff check .

      - name: Mypy (non-blocking)
        run: |
          mypy server || true

      - name: Pytest with coverage
        run: |
          pytest -q --maxfail=1 --disable-warnings -m "not slow" -k "not slow" \
            --cov=server --cov=cv_engine --cov-report=term-missing --cov-report=xml \
            --cov-fail-under=80

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml
          if-no-files-found: ignore
          retention-days: 7
